# Generated by Django 2.2.13 on 2020-07-10 21:01

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200612_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='contained_allergen',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('NA', 'Keine'), ('nuts', 'Nüsse'), ('glut', 'Gluten'), ('lact', 'Kuhmilch'), ('fish', 'Fisch'), ('egg', 'Hühnereier')], max_length=26),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cuisine',
            field=models.CharField(choices=[('DEF', ''), ('INT', 'Internationale Küche'), ('ASI', 'Asiatische Küche'), ('AFR', 'Afrikanische Küche'), ('EUR', 'Europäische Küche'), ('AME', 'Amerikanische Küche'), ('SUA', 'Südamerikanische Küche')], default='DEF', max_length=30),
        ),
    ]
