# Generated by Django 2.2.13 on 2020-07-12 19:28

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200710_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='contained_allergen',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('NA', 'Keine'), ('nuts', 'Nüsse'), ('glut', 'Gluten'), ('lact', 'Laktose'), ('fish', 'Fisch'), ('egg', 'Hühnereier')], max_length=26),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
