# Generated by Django 2.2.13 on 2020-07-13 08:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(1000)], verbose_name='Menge'),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='ingredient',
            field=models.CharField(max_length=30, verbose_name='Bezeichnung'),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='unit',
            field=models.CharField(max_length=10, verbose_name='Einheit(en)'),
        ),
    ]
